import Head from "next/head";
import Navbar from "../components/Navbar";
import Categories from "../views/homepage/Categories";
import NewLaunches from "../views/homepage/NewLaunches";
import TrendingNow from "../views/homepage/TrendingNow";
import Footer from "../components/Footer";




export default function Home() {
  return (
    <>
      <Head>
        <title>Tomorrow India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Categories/>
      <NewLaunches/>
      <TrendingNow/>
      <Footer/>


     
    </>
  );
}



